AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  OrphanedLogGroupsCollector:
    Type: AWS::Serverless::Function
    Properties:
      Description: Delete orphaned log groups
      CodeUri: code/
      Handler: handler.lambda_handler
      Runtime: python3.7
      Timeout: 900
      Tracing: Active
      Policies:
        - AWSLambdaBasicExecutionRole
        - Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action:
                - ec2:DescribeRegions
                - logs:DescribeLogGroups
                - logs:DeleteLogGroup
                - lambda:ListFunctions
                - apigateway:GET
              Resource: '*'
