Transform: AWS::Serverless-2016-10-31

Description: Orphaned Log Groups Collector deletes AWS Lambda and Amazon RDS related log groups not associated with any resources in the AWS Account.

Metadata:
  AWS::ServerlessRepo::Application:
    Name: orphaned-log-groups-collector
    Description: Orphaned Log Groups Collector deletes AWS Lambda and Amazon RDS related log groups not associated with any resources in the AWS Account.
    Author: Michal Gorski
    SpdxLicenseId: Apache-2.0
    LicenseUrl: LICENSE
    ReadmeUrl: README.md
    Labels: [ 'lambda','rds','cloudwatch','cron' ]
    HomePageUrl: https://github.com/mgorski-mg/aws-orphaned-log-groups-collector
    SemanticVersion: 2.1.0
    SourceCodeUrl: https://github.com/mgorski-mg/aws-orphaned-log-groups-collector

Parameters:
  SchedulerCronParameter:
    Type: String
    Description: Enter scheduler cron expression. Default is cron(0 0 1 * ? *).
    Default: cron(0 0 1 * ? *)
  SchedulerEnabledParameter:
    Type: String
    Description: Enable scheduler. Default is ENABLED.
    Default: DISABLED
    AllowedValues: [ ENABLED, DISABLED ]

Resources:
  OrphanedLogGroupsCollector:
    Type: AWS::Serverless::Function
    Properties:
      Description: Delete orphaned log groups
      CodeUri: code/
      Handler: handler.lambda_handler
      Runtime: python3.9
      Timeout: 900
      MemorySize: 128
      Tracing: Active
      Architectures:
        - arm64
      # SAM not used because of a bug in Enabled: !Ref SchedulerEnabledParameter - https://github.com/awslabs/serverless-application-model/issues/1360
      #      Events:
      #        Schedule:
      #          Type: Schedule
      #          Properties:
      #            Name: Scheduler
      #            Description: Scheduler
      #            Enabled: !Ref SchedulerEnabledParameter
      #            Schedule: !Ref SchedulerCronParameter
      #            Input: '{"dry_run": false}'
      Policies:
        - AWSLambdaBasicExecutionRole
        - Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action:
                - ec2:DescribeRegions
                - logs:DescribeLogGroups
                - logs:DeleteLogGroup
                - lambda:ListFunctions
                - rds:DescribeDBClusters
              Resource: '*'

  OrphanedLogGroupsCollectorLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${OrphanedLogGroupsCollector}
      RetentionInDays: 180

  Scheduler:
    Type: AWS::Events::Rule
    Properties:
      ScheduleExpression: !Ref SchedulerCronParameter
      State: !Ref SchedulerEnabledParameter
      Targets:
        - Id: Scheduler
          Arn: !GetAtt OrphanedLogGroupsCollector.Arn
          Input: '{"dry_run": false}'

  SchedulerPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref OrphanedLogGroupsCollector
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt Scheduler.Arn